---
title: 'Modelling Coffee Agroforestry in Central America with CAF2021'
subtitle: 'Progress report III for project SEACAF, sub-contract B0554x4'
author:
- Marcel van Oijen^[Independent researcher, Edinburgh, UK - VanOijenMarcel@gmail.com]
date: '`r Sys.Date()`'
output:
  pdf_document:
    fig_crop: false
    fig_caption: yes
    keep_tex: no
    number_sections: yes
    toc: yes
  word_document:
    reference_docx: word-styles-reference-01.docx
  html_document: default
fontsize: 11pt
geometry: margin=1in
csl: environmental-modelling-and-software.csl
bibliography: [Avocado.bib,Banana.bib,SEACAF.bib]
---

```{r, include=FALSE}
  knitr::opts_chunk$set(echo=F,results="asis",warning=FALSE,message=FALSE)
  library( geosphere )
  library( readxl    )
  library( tidyverse )
```

\clearpage

# Weather data

```{r, eval=T}
  dir_weatherstations <- "weather/Climatic_Data/"
    dir_C_Icafe   <- "CostaRica/Icafe/"
    dir_C_IMN     <- "CostaRica/IMN/"
    dir_G_Anacafe <- "Guatemala/Anacafe/"

  dir_Icafe     <- paste0( dir_weatherstations, dir_C_Icafe   ) 
  dir_IMN       <- paste0( dir_weatherstations, dir_C_IMN     )
  dir_Anacafe   <- paste0( dir_weatherstations, dir_G_Anacafe ) 
  
  file_Icafe    <- "Datos confidenciales CLIMA-ICAFE- Convenio CATIE.xlsx"
  files_IMN.TMIN <- list.files( dir_IMN, pattern="*TMIN_TMAX_RAIN.xlsx" )
  files_IMN.TMAX <- list.files( dir_IMN, pattern="*TMIN_TMAX_RAIN.xlsx" )
  files_IMN.RAIN <- list.files( dir_IMN, pattern="*RAIN.xlsx" )
    n_IMN.TMIN   <- length( files_IMN.TMIN )
    n_IMN.TMAX   <- length( files_IMN.TMAX )
    n_IMN.RAIN   <- length( files_IMN.RAIN )
  files_Anacafe <- list.files( dir_Anacafe )
    n_Anacafe   <- length( files_Anacafe )
```

```{r, eval=T}
  df_Icafe       <- read_excel( paste0(dir_Icafe,file_Icafe) )
  stations_Icafe <- unique(df_Icafe$Estacion) ; n_Icafe <- length(stations_Icafe)

  list_Icafe    <- vector( "list", n_Icafe    )
  list_IMN.TMIN <- vector( "list", n_IMN.TMIN )
  list_IMN.TMAX <- vector( "list", n_IMN.TMAX )
  list_IMN.RAIN <- vector( "list", n_IMN.RAIN )
  list_Anacafe  <- vector( "list", n_Anacafe  )

  for( s in 1:n_Icafe ) {
    list_Icafe[[s]]   <- df_Icafe %>% filter( Estacion==stations_Icafe[s] ) }
  for( s in 1:n_IMN.TMIN ) {
    fs <- paste0(dir_IMN,files_IMN.TMIN[s])
    list_IMN.TMIN[[s]] <- read_excel( fs, sheet="TMIN", skip=1,
                                      col_type="numeric" ) }
  for( s in 1:n_IMN.TMAX ) {
    fs <- paste0(dir_IMN,files_IMN.TMAX[s])
    list_IMN.TMAX[[s]] <- read_excel( fs, sheet="TMAX", skip=1,
                                      col_type="numeric" ) }
  for( s in 1:n_IMN.RAIN ) {
    fs <- paste0(dir_IMN,files_IMN.RAIN[s])
    list_IMN.RAIN[[s]] <- read_excel( fs, sheet="RAIN", skip=1,
                                      col_type="numeric" ) }
  for( s in 1:n_Anacafe ) {
    list_Anacafe[[s]] <- read_csv( paste0(dir_Anacafe,files_Anacafe[s]) ) }
```

```{r}
  ny_Icafe <- rep( NA, n_Icafe )
  for( s in 1:n_Icafe)    { r <- range( list_Icafe[[s]]$year )
    ny_Icafe[s]   <- 1 + r[2] - r[1] }

  ny_IMN <- rep( NA, n_IMN.RAIN )
  for( s in 1:n_IMN.RAIN) { r <- range( list_IMN.RAIN[[s]]$Año )
    ny_IMN[s]     <- 1 + r[2] - r[1] }
  
  ny_Anacafe <- rep( NA, n_Anacafe )
  for( s in 1:n_Anacafe)  { r <- range( list_Anacafe[[s]][,"year"] )
    ny_Anacafe[s] <- 1 + r[2] - r[1] }
```


```{r, eval=T}
  for( s in 1:n_Icafe ) {
    list_Icafe[[s]] <- list_Icafe[[s]] %>%
      rename( ST = Estacion ) %>%
      rename( TMAX    = "Temperatura máxima °C" ) %>%
      rename( TMIN    = "Temperatura mínima °C" ) %>%
      rename( RAIN    = "Lluvia mm" ) %>%
      dplyr::select( ST, year, month, TMIN, TMAX, RAIN ) %>%
      group_by( ST, year, month ) %>%
      summarize( TMIN = mean(TMIN,na.rm=T),
                 TMAX = mean(TMAX,na.rm=T),
                 RAIN = sum (RAIN,na.rm=T) ) %>%
      mutate( lat    = ifelse(ST=="Orosi"      ,  9.78529,
                       ifelse(ST=="Atirro"     ,  9.8612 ,
                       ifelse(ST=="Santa Rosa" ,  9.92852,
                       ifelse(ST=="San Ramón"  , 10.06455,
                       ifelse(ST=="Naranjo"    , 10.10778,
                       ifelse(ST=="Frailes"    ,  9.75   ,
                       ifelse(ST=="San Carlos" ,  9.62661,
                       ifelse(ST=="San Lorenzo",  9.6414 ,
                       ifelse(ST=="Dota"       ,  9.65056,
                              NA ))))))))) ) %>%
      mutate( lon    = ifelse(ST=="Orosi"      , -83.84652,
                       ifelse(ST=="Atirro"     , -83.6358 ,
                       ifelse(ST=="Santa Rosa" , -83.69964,
                       ifelse(ST=="San Ramón"  , -84.47379,
                       ifelse(ST=="Naranjo"    , -84.38361,
                       ifelse(ST=="Frailes"    , -84.05306,
                       ifelse(ST=="San Carlos" , -84.09163,
                       ifelse(ST=="San Lorenzo", -84.02354,
                       ifelse(ST=="Dota"       , -83.9575 ,
                              NA ))))))))) ) %>%
      dplyr::select( ST, lat, lon, year, month, TMIN, TMAX, RAIN )
  }

  do.call( rbind, list_Icafe )
```

```{r, eval=T}
  for(s in 1:n_IMN.TMIN) {
    list_IMN.TMIN[[s]] <- list_IMN.TMIN[[s]] %>%
      rename( month = Mes ) %>%
      rename( year = Año ) %>%
      mutate( TMIN = rowMeans( select(.,starts_with("D")), na.rm=T) ) %>%
      dplyr::select( year, month, TMIN ) %>%
      group_by ( month ) %>%
      mutate( ST = substr(files_IMN.TMAX[s],1,5) ) %>%
      dplyr::select( ST, year, month, TMIN ) }

  for(s in 1:n_IMN.TMAX) {
    list_IMN.TMAX[[s]] <- list_IMN.TMAX[[s]] %>%
      rename( month = Mes ) %>%
      rename( year = Año ) %>%
      mutate( TMAX = rowMeans( select(.,starts_with("D")), na.rm=T) ) %>%
      dplyr::select( year, month, TMAX ) %>%
      group_by ( month ) %>%
      mutate( ST = substr(files_IMN.TMAX[s],1,5) ) %>%
      dplyr::select( ST, year, month, TMAX ) }

  for(s in 1:n_IMN.RAIN) {
    list_IMN.RAIN[[s]] <- list_IMN.RAIN[[s]] %>%
      rename( month = Mes ) %>%
      rename( year = Año ) %>%
      mutate( RAIN = rowSums( select(.,starts_with("D")), na.rm=T) ) %>%
      dplyr::select( year, month, RAIN ) %>%
      group_by ( month ) %>%
      mutate( ST = substr(files_IMN.RAIN[s],1,5) ) %>%
      dplyr::select( ST, year, month, RAIN ) }

  list_IMN <- list_IMN.RAIN
  for(s in 1:n_IMN.RAIN) {
    list_IMN[[s]] <- list_IMN[[s]] %>%
      mutate( lat = ifelse(ST==73048,  9.838611,
                    ifelse(ST==73123,  9.852222,
                    ifelse(ST==84187, 10.005   ,
                    ifelse(ST==84189, 10.13733 ,
                    ifelse(ST==88039,  9.766667,
                    ifelse(ST==88047,  9.736667,
                           NA )))))) ) %>%
      mutate( lon = ifelse(ST==73048, -83.90722,
                    ifelse(ST==73123, -83.90861,
                    ifelse(ST==84187, -84.26556,
                    ifelse(ST==84189, -84.1935 ,
                    ifelse(ST==88039, -84.09056,
                    ifelse(ST==88047, -84.00056,
                           NA )))))) ) %>%
      dplyr::select( ST, lat, lon, year, month, RAIN )
    }
  for(s in 1:n_IMN.RAIN) {
    sTMIN <- which( files_IMN.RAIN[s] == files_IMN.TMIN )
    if (length(sTMIN>0)) {
      list_IMN[[s]] <- list_IMN[[s]] %>%
        inner_join( list_IMN.TMIN[[sTMIN]], by=c("ST","year","month") ) %>%
        dplyr::select(ST,lat,lon,year,month,TMIN,RAIN)
    }
    sTMAX <- which( files_IMN.RAIN[s] == files_IMN.TMAX )
    if (length(sTMAX>0)) {
      list_IMN[[s]] <- list_IMN[[s]] %>%
        inner_join( list_IMN.TMAX[[sTMAX]], by=c("ST","year","month") ) %>%
        dplyr::select(ST,lat,lon,year,month,TMIN,TMAX,RAIN)
    }
  }
  
  do.call( rbind, list_IMN )
```

```{r, eval=T}
  for( s in 1:n_Anacafe ) {
    list_Anacafe[[s]] <- list_Anacafe[[s]] %>%
      rename( ST    = ID_ESTACION ) %>%
      rename( lat   = LATITUD     ) %>%
      rename( lon   = LONGITUD    ) %>%
      rename( TMEAN = "TMP" ) %>%
      rename( RAIN  = "RNF" ) %>%
      select( ST, lat, lon, year, month, TMEAN, RAIN ) %>%
      group_by( ST, lat, lon, year, month ) %>%
      summarize( TMEAN = mean(TMEAN,na.rm=T),
                 RAIN  = sum (RAIN ,na.rm=T) ) %>%
      dplyr::select( ST, lat, lon, year, month, TMEAN, RAIN )
  }

  do.call( rbind, list_Anacafe )
```

```{r, eval=T}
  df.ym <- function(df,y,m) {df %>% filter(year==y) %>% filter(month==m)}
```

```{r, eval=T}
  # Weather stations Costa Rica and their distance from Turrialba
  df=C.a

  lonlat_C.ST <- df[ c("lon","lat") ]
  coordsT     <- c( -83.68,  9.89  ) # Longitude, Latitude
  dist.T      <- as.vector( distm( coordsT, lonlat_C.ST ) ) / 1000
  df          <- df %>% add_column( dist=dist.T )

  par( mfrow=c(3,4), mar=c(3,3,3,1), mgp=c(2,1,0) )

  country="C" ; xvar="dist"
  
  yvar="TMIN.a" ; yrange <- range( df[[yvar]], na.rm=T )
  for(m in 1:12) {
    df.m <- df.ym(df,2019,m) ; x = df.m[[xvar]] ; y = df.m[[yvar]]
    plot( x, y, main=paste0(country,":",yvar," ",m),
          xlab=xvar, ylab="", ylim=yrange )
    abline(h=0,col="black")
    lm <- lm( y ~ x )
    abline( lm$coefficients[1], lm$coefficients[2], col="blue" )
  }
  
  yvar="TMAX.a" ; yrange <- range( df[[yvar]], na.rm=T )
  for(m in 1:12) {
    df.m <- df.ym(df,2019,m) ; x = df.m[[xvar]] ; y = df.m[[yvar]]
    plot( x, y, main=paste0(country,":",yvar," ",m),
          xlab=xvar, ylab="", ylim=yrange )
    abline(h=0,col="black")
    lm <- lm( y ~ x )
    abline( lm$coefficients[1], lm$coefficients[2], col="blue" )
  }
  
  yvar="RAIN.a" ; yrange <- range( df[[yvar]], na.rm=T )
  for(m in 1:12) {
    df.m <- df.ym(df,2019,m) ; x = df.m[[xvar]] ; y = df.m[[yvar]]
    plot( x, y, main=paste0(country,":",yvar," ",m),
          xlab=xvar, ylab="", ylim=yrange )
    abline(h=0,col="black")
    lm <- lm( y ~ x )
    abline( lm$coefficients[1], lm$coefficients[2], col="blue" )
  }
```

```{r, eval=T}
  # Weather stations Guatemala and their distance from farm 170
  df=G.a

  lonlat_G.ST <- df[ c("lon","lat") ]
  coordsG170  <- c( -90.44, 14.429 ) # Longitude, Latitude
  dist.170    <- as.vector( distm( coordsG170, lonlat_G.ST ) ) / 1000
  df          <- df %>% add_column( dist=dist.170 )

  par( mfrow=c(3,4), mar=c(3,3,3,1), mgp=c(2,1,0) )

  country="G" ; xvar="dist"
  
  yvar="TMEAN.a" ; yrange <- range( df[[yvar]], na.rm=T )
  for(m in 1:12) {
    df.m <- df.ym(df,2019,m) ; x = df.m[[xvar]] ; y = df.m[[yvar]]
    plot( x, y, main=paste0(country,":",yvar," ",m),
          xlab=xvar, ylab="", ylim=yrange )
    abline(h=0,col="black")
    lm <- lm( y ~ x )
    abline( lm$coefficients[1], lm$coefficients[2], col="blue" )
  }
  
  yvar="RAIN.a" ; yrange <- range( df[[yvar]], na.rm=T )
  for(m in 1:12) {
    df.m <- df.ym(df,2019,m) ; x = df.m[[xvar]] ; y = df.m[[yvar]]
    plot( x, y, main=paste0(country,":",yvar," ",m),
          xlab=xvar, ylab="", ylim=yrange )
    abline(h=0,col="black")
    lm <- lm( y ~ x )
    abline( lm$coefficients[1], lm$coefficients[2], col="blue" )
  }
```

```{r, eval=T}
  C.a.mean2019mon <- C.a %>%
    filter( year == 2019 ) %>%
    group_by( month ) %>%
    summarize( TMIN.a = mean(TMIN.a,na.rm=T),
               TMAX.a = mean(TMAX.a,na.rm=T),
               RAIN.a = mean(RAIN.a,na.rm=T) ) %>%
    as.matrix()
  
  knitr::kable( C.a.mean2019mon )
```

```{r, eval=T}
  G.a.mean2019mon <- G.a %>%
    filter( year == 2019 ) %>%
    group_by( month ) %>%
    summarize( TMEAN.a = mean(TMEAN.a,na.rm=T),
               RAIN.a  = mean(RAIN.a ,na.rm=T) ) %>%
    as.matrix()
  
  knitr::kable( G.a.mean2019mon )
```

## Extending farm weather files by two years (2019, 2020)

For 2019 we use the country-average monthly anomalies, for 2020 the climatic average.

```{r, eval=T}
  monl   <- c( 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31 )
  monend <- cumsum( monl ) ; monstart <- c( 1, head(monend+1,-1) )
  mon    <- function(doy) { which((doy>=monstart) & (doy<=monend)) }
```

```{r, eval=T}
  nf <- length( df_C.f$code )

  for(f in 1:nf) {
    w.f                <- df_C.f$weather.WC[[f]]
    ncol               <- dim(w.f)[2]
    meanyear           <- matrix( NA, 365, ncol )
    colnames(meanyear) <- colnames(w.f)
    for(d in 1:365) {
      meanyear[d,] <- colMeans( w.f[ which(w.f[,"doy"]==d), ] )
    }
    anom2019 <- matrix(0,365,ncol) ; colnames(anom2019) <- colnames(w.f)
    for(d in 1:365) {
      anom2019[d,"TMIN"] <- C.a.mean2019mon[ mon(d), "TMIN.a" ]
      anom2019[d,"TMAX"] <- C.a.mean2019mon[ mon(d), "TMAX.a" ]
      anom2019[d,"RAIN"] <- C.a.mean2019mon[ mon(d), "RAIN.a" ] / monl[mon(d)]
    }
    year2020          <- meanyear            ; year2020[,"year"] <- 2020
    year2019          <- meanyear + anom2019 ; year2019[,"year"] <- 2019
    year2019[,"RAIN"] <- pmax( year2019[,"RAIN"], 0 )
    w.f               <- rbind( w.f, year2019, year2020 )
    df_C.f$weather.WC[[f]] <- w.f
    # y20    <- year2020[,"RAIN"] ; y19 <- year2019[,"RAIN"]
    # yrange <- range(y20,y19)
    # plot( y20, main=paste0("RAIN(",f,")"), ylim=yrange, xlab="", ylab="" )
    # points( y19,col="red" )
  }
```

```{r, eval=T}
  nf <- length( df_G.f$code )

  par( mfrow=c(5,5), mar=c(2,1,1,1) )

  for(f in 1:nf) {
    w.f                <- df_G.f$weather.WC[[f]]
    ncol               <- dim(w.f)[2]
    meanyear           <- matrix( NA, 365, ncol )
    colnames(meanyear) <- colnames(w.f)
    for(d in 1:365) {
      meanyear[d,] <- colMeans( w.f[ which(w.f[,"doy"]==d), ] )
    }
    anom2019 <- matrix(0,365,ncol) ; colnames(anom2019) <- colnames(w.f)
    for(d in 1:365) {
      anom2019[d,"TMIN"] <- G.a.mean2019mon[ mon(d), "TMEAN.a" ]
      anom2019[d,"TMAX"] <- G.a.mean2019mon[ mon(d), "TMEAN.a" ]
      anom2019[d,"RAIN"] <- G.a.mean2019mon[ mon(d), "RAIN.a"  ] / monl[mon(d)]
    }
    year2020          <- meanyear            ; year2020[,"year"] <- 2020
    year2019          <- meanyear + anom2019 ; year2019[,"year"] <- 2019
    year2019[,"RAIN"] <- pmax( year2019[,"RAIN"], 0 )
    w.f               <- rbind( w.f, year2019, year2020 )
    df_G.f$weather.WC[[f]] <- w.f
    # y20    <- year2020[,"TMIN"] ; y19 <- year2019[,"TMIN"]
    # yrange <- range(y20,y19)
    # plot( y20, main=paste0("TMIN(",f,")"), ylim=yrange, xlab="", ylab="" )
    # points( y19,col="red" )
  }
```
