---
title: 'CAF2021: Input variables'
author:
- Marcel van Oijen; VanOijenMarcel@gmail.com
date: '`r Sys.Date()`'
output:
  pdf_document:
    fig_crop: false
    fig_caption: yes
    keep_tex: no
    number_sections: yes
    toc: yes
  word_document:
    reference_docx: word-styles-reference-01.docx
  html_document: default
fontsize: 11pt
geometry: margin=1in
---

# Turrialba (Costa Rica): Long-term coffee agroforestry experiment

## Weather

```{r, echo=FALSE, out.width="100%", fig.cap="\\label{FigWeather}Weather at CATIE 2000-2017."}
  file_weather <- 'weather/weather_Turrialba_2000_2017.txt'
  df_weather   <- read.table( file_weather, header=TRUE )
  Time         <- with( df_weather, year + (doy-0.5)/366 )

  par( mfrow=c(2,3), mar=c(2,4,0,1) )
  plot( Time, df_weather$GR  , ylab="GR (MJ m-2 d-1)", cex=0.1, xlab="", xaxt="n" )
  plot( Time, df_weather$TMIN, ylab="TMIN (degC)"    , cex=0.1, xlab="", xaxt="n" )
  plot( Time, df_weather$TMAX, ylab="TMAX (degC)"    , cex=0.1, xlab="", xaxt="n" )
  plot( Time, df_weather$VP  , ylab="VP (kPa)"       , cex=0.1, xlab="" )
  plot( Time, df_weather$WN  , ylab="WN (m s-1)"     , cex=0.1, xlab="" )
  plot( Time, df_weather$RAIN, ylab="RAIN (mm d-1)"  , cex=0.1, xlab="" )
```

- We created a file with daily weather data 2000-2017 for five variables: radiation, temperature, atmospheric vapour pressure, wind speed, rainfall.
- For the period Jan 2000 - April 2014, we used a daily weather data file created by Oriana Ovalle.
- For the period May 2014 - May 2017, we used data downloaded from the CATIE website: daily data for rain, mostly monthly data for the other four variables.
- For the period June to Dec 2017, we used the median values of the same-day values from all preceding years.
- The wind speed data are clearly unreliable. There is evidence of sensor drift over time toward unrealistically low values.
- The absence of daily data for most variables May 2014-Dec 2016 is a problem.
- The absence of any data from June 2017 is a problem.
- Data from the weather station 73103 differed too much from CATIE data (in time periods and for variables where both had data) to be useful for gap-filling.

## Soil and management

- There was large spatial variation on the CATIE site, as we can see from very large differences between the three blocks of the experiment. We ignored this variation and used the same soil property values for all treatments.
- For the fertilization levels of the AC and MC treatments, we used the values in the Ovalle model initialisation files (AC: 90+90+100 kg N ha-1 y-1; MC: 45+45+60 kg N ha-1 y-1). We assumed that the annual N-additions in the MO treatment were 20% of MC, and were zero in BO.
